// frontend_1/src/app/components/tweet/tweet.component.ts
import { Component, OnInit } from '@angular/core';
import { TwitterService } from 'src/app/service/twitter-service.service';

@Component({
  selector: 'app-tweet',
  templateUrl: './tweet.component.html',
  styleUrls: ['./tweet.component.scss']
})
export class TweetComponent implements OnInit {
  tweet:string = '';
  notificationMsg:string='';
  isError : boolean = false;

  constructor(private twitterService:TwitterService) { }

  ngOnInit(): void {
  }

  public tweetMsg(){
    this.notificationMsg ='';
    this.twitterService.userTweet(this.tweet).subscribe((resp)=>{
      let respObj = JSON.parse(resp);
      let status = respObj.status;
      let message = respObj.message;
      if(status == this.twitterService.successFlag){
        this.reset();
        this.notificationMsg = 'You have successfully tweeted a msg';
      }
      else{
        this.isError = true;
        this.notificationMsg = message;
      }
      
      
      //this.twitterService.storeUser(userId);
      //this.router.navigate(['/login']);
    })
}

public reset(){
  this.tweet='';
}

  

}

<div class="follow-wrapper container-fluid">
    <div class="heading-follow">Tweet</div>
    <div class="shadow p-3">
      <div class="mb-3">
        <label htmlFor="exampleInputEmail1" class="form-label">Tweet</label>
        
        <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" [(ngModel)]='tweet' />
        
      </div>
      <div id="emailHelp" *ngIf="notificationMsg.length>0" [ngClass]="{'errorMsg':(isError), 'successMsg':(!isError), 'form-text':true}">{{notificationMsg}}</div>
      <button type="submit" class="btn btn-primary" (click)='tweetMsg()'>Tweet</button>
    </div>
  </div>

// frontend/src/components/Tweet/Tweet.tsx
import './Tweet.scss';

const Tweet = () => (
  <div className="follow-wrapper container-fluid">
  <div className="heading-follow">Tweet</div>
  <div className="shadow p-3">
    <div className="mb-3">
      <label htmlFor="exampleInputEmail1" className="form-label">Username</label>
      <input type="text" className="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" />
      <div id="emailHelp" className="form-text">We'll never share your email with anyone else.</div>
    </div>
    <button type="submit" className="btn btn-primary">Submit</button>
  </div>
</div>
);

export default Tweet;
