// frontend_1/src/app/components/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { TwitterService } from 'src/app/service/twitter-service.service';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss']
})
export class HomeComponent implements OnInit {

  constructor(private twitterService:TwitterService, private router:Router) { 
    
  }

  ngOnInit(): void {
    if(!this.twitterService.isLoggedIn()){
      this.router.navigate(["/login"]);
    }
  }

}

<div class="container">
    <div class="row">
      <div class="col-lg-7 col-mg-7">
        <app-tweet></app-tweet>
        <app-feed></app-feed>
      </div>
      <div class="col-lg-5 col-mg-5">
      <app-follow></app-follow>
      <app-search></app-search>
      </div>
    </div>
</div>

// frontend/src/components/Home/Home.tsx
import './Home.scss';
import Feed from '../Feed/Feed'
import Follow from '../Follow/Follow'
import Tweet from '../Tweet/Tweet'

const Home = () => (
  <div className="container">
    <div className="row">
      <div className="col-lg-7 col-mg-7">
        <Feed />
      </div>
      <div className="col-lg-5 col-mg-5">
      <Tweet />
      <Follow />  
      </div>
    </div>
  </div>
);

export default Home;
