// frontend/src/components/Navbar/Navbar.tsx
import './Navbar.scss';

const Navbar = () => (
  <div className="navbar-wrapper">
        <div className="container-fluid">
          <nav className={"navbar navbar-expand-lg"}>
            <div className="container">
              <a className="navbar-brand" href="#">Twitter Clone</a>
              <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span className={"navbar-toggler-icon"}></span>
              </button>
              <div className={"collapse navbar-collapse"} id="navbarSupportedContent">
                <ul className="navbar-nav me-auto mb-2 mb-lg-0">
                  <li className="nav-item">
                    <a className={"nav-link active"} aria-current="page" href="/home">Home</a>
                  </li>
                </ul>
                <li className={"nav-item d-flex"}>
                  <a className="nav-link" href="#">Login</a>
                </li>
                <li className={"nav-item d-flex"}>
                  <a className="nav-link" href="#">Logout</a>
                </li>
              </div>
            </div>
          </nav>
        </div>
      </div>
);

export default Navbar;

// frontend_1/src/app/components/navbar/navbar.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { TwitterService } from 'src/app/service/twitter-service.service';

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.scss']
})
export class NavbarComponent implements OnInit {

  constructor(private twitterService:TwitterService, private router: Router) { }

  ngOnInit(): void {
  }

  isActive(){
    //console.log(this.twitterService.isLoggedIn());
    return this.twitterService.isLoggedIn();
  }

  logout(){
    this.twitterService.removeUser();
    this.router.navigate(["/login"]);
  }
}

<div class="navbar-wrapper">
    <div class="container-fluid">
      <nav class="navbar navbar-expand-lg">
        <div class="container">
          <a class="navbar-brand" href="#">Twitter Clone</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a *ngIf="isActive()" class="nav-link" active aria-current="page" routerLink="/login">Home</a>
              </li>
            </ul>
            <li *ngIf="!isActive()" class="nav-item d-flex">
              <a class="nav-link" routerLink="/login">Login</a>
            </li>
            <li *ngIf="isActive()" class="nav-item d-flex">
              <a class="nav-link" (click)='logout()'>Logout</a>
            </li>
            <li *ngIf="!isActive()" class="nav-item d-flex">
                <a class="nav-link" routerLink="/register">Register</a>
            </li>
          </div>
        </div>
      </nav>
    </div>
  </div>
