// frontend_1/src/app/components/follow/follow.component.ts
import { Component, OnInit } from '@angular/core';
import { resetFakeAsyncZone } from '@angular/core/testing';
import { TwitterService } from 'src/app/service/twitter-service.service';

@Component({
  selector: 'app-follow',
  templateUrl: './follow.component.html',
  styleUrls: ['./follow.component.scss']
})
export class FollowComponent implements OnInit {
  username: string = "";
  notificationMsg: string = '';
  isError: boolean = false;

  constructor(private twitterService: TwitterService) { }

  ngOnInit(): void {
  }

  follow() {
    this.twitterService.userFollow(this.username).subscribe((resp) => {
      console.log(resp);
      let respObj = JSON.parse(resp);
      let status = respObj.status;
      let message = respObj.message;
      if (status == this.twitterService.successFlag) {
        this.reset();
      }
      else {
        this.isError = true;
      }
      this.notificationMsg = message;
    })
  }


  reset() {
    this.username = '';
  }

}

<div class="follow-wrapper container-fluid">
    <div class="heading-follow">Follow User</div>
    <div class="shadow p-3">
        
      <div class="mb-3">
        <label htmlFor="exampleInputEmail1" class="form-label">Username</label>
        <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" [(ngModel)]='username'/>
        <div id="emailHelp" *ngIf="notificationMsg.length>0" [ngClass]="{'errorMsg':(isError), 'successMsg':(!isError), 'form-text':true}">{{notificationMsg}}</div>
      </div>
      <button type="submit" class="btn btn-primary"(click)="follow()">Follow</button>
    </div>
  </div>

// frontend/src/components/Follow/Follow.tsx
import './Follow.scss';

const Follow = () => (
  <div className="follow-wrapper container-fluid">
  <div className="heading-follow">Follow User</div>
  <div className="shadow p-3">
    <div className="mb-3">
      <label htmlFor="exampleInputEmail1" className="form-label">Username</label>
      <input type="text" className="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" />
      <div id="emailHelp" className="form-text">We'll never share your email with anyone else.</div>
    </div>
    <button type="submit" className="btn btn-primary">Submit</button>
  </div>
</div>
);

export default Follow;
