// frontend/src/components/Login/Login.tsx
import './Login.scss';

const Login = () => (
  <div className="container d-flex justify-content-center">
    <div className="shadow p-3 col-lg-6 col-md-8 col-sm-12">
      <div className="mb-3">
        <label htmlFor="exampleInputEmail1" className="form-label">Username</label>
        <input type="text" className="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" />
        <div id="emailHelp" className="form-text">We'll never share your email with anyone else.</div>
      </div>
      <div className="mb-3">
        <label htmlFor="exampleInputPassword1" className="form-label">Password</label>
        <input type="password" className="form-control" id="exampleInputPassword1" />
      </div>
      <div className="mb-3 form-check">
        <input type="checkbox" className="form-check-input" id="exampleCheck1" />
        <label className="form-check-label" htmlFor="exampleCheck1">Check me out</label>
      </div>
      <button type="submit" className="btn btn-primary">Submit</button>
    </div>
  </div>
);

export default Login;

// frontend_1/src/app/components/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { TwitterService } from 'src/app/service/twitter-service.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent implements OnInit {
  username:string='';
  password:string='';
  notificationMsg:string='';
  isError : boolean = false;
  constructor(private twitterService:TwitterService, private router:Router) { }

  ngOnInit(): void {
    if(this.twitterService.isLoggedIn()){
      this.router.navigate(["/home"]);
    }
  }

  login(){
    this.twitterService.userLogin(this.username,this.password).subscribe((resp)=>{
      console.log(resp);
      let respObj = JSON.parse(resp);
        let status = respObj.status;
        let message = respObj.message;
        let userID = respObj.userID;
        if(status == this.twitterService.successFlag){
          this.reset();
          this.twitterService.storeUser(userID);
          this.router.navigate(["/home"]);
        }
        else{
          this.isError = true;
          this.notificationMsg = message;
        }
    })
  }

  public reset(){
    this.username = '';
    this.password = '';
    this.isError = false;
  }

}


<div class="login-wrapper container d-flex justify-content-center">
    <div class="shadow p-3 col-lg-6 col-md-8 col-sm-12">
        <h2 class="heading">Login</h2>

       
        <div class="mb-3">
            <div id="emailHelp" *ngIf="notificationMsg.length>0" [ngClass]="{'errorMsg':(isError), 'successMsg':(!isError), 'form-text':true}">{{notificationMsg}}</div>
            <label htmlFor="exampleInputEmail1" class="form-label">Username</label>
            <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" [(ngModel)]='username'/>
             
        </div>
        <div class="mb-3">
            <label htmlFor="exampleInputPassword1" class="form-label">Password</label>
            <input type="password" class="form-control" id="exampleInputPassword1" [(ngModel)]='password' />
        </div>
        <div class="mb-3 form-check">
            <input type="checkbox" class="form-check-input" id="exampleCheck1" />
            <label class="form-check-label" htmlFor="exampleCheck1">Check me out</label>
        </div>
        <button type="submit" class="btn btn-primary" (click)='login()'>Submit</button>
    </div>
</div>
